@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title Initial state

package ModelManager {
    class State1 as "<u>backupAddressBook:AddressBook</u>"
    class State2 as "<u>addressBook:AddressBook</u>"
}
State1 -[hidden]right-> State2

@end
